import json,pathlib,hashlib,collections,re,datetime,argparse
from git_tree_identity import tree_root_sha1
ap=argparse.ArgumentParser();ap.add_argument('source_root',type=pathlib.Path);args=ap.parse_args()
BASE=args.source_root;META=BASE/'private/metadata'
sources=[]
wiki_receipt=json.load(open(BASE/'private/wiki-acquisition-receipt.json'))
census=json.load(open(BASE/'public/wiki-census.aggregate.json'))
for r in wiki_receipt['results']:
    ident=r['source_id'];a=json.load(open(META/(ident+'.json')));rep=next(x for x in census['reports'] if x['source_id']==ident);is_news='wikinews' in ident
    sources.append(dict(source_id=ident,priority=1,status='acquired_and_structurally_censused_not_admitted',source_family='wikimedia',genre=['citizen_news','translated_news','news_synthesis'] if is_news else ['travel_guide','instructional_reference'],source_urls=['https://archive.org/metadata/'+ident,r['source_url']],version=dict(snapshot_date='2021-10-20',archive_publicdate=a['metadata']['publicdate'],historical_license_revision=r['historical_license_revision'],historical_license_url=('https://zh.wikinews.org/w/index.php?oldid=' if is_news else 'https://zh.wikivoyage.org/w/index.php?oldid=')+str(r['historical_license_revision']),sha256=r['sha256'],sha1=r['sha1'],md5=r['md5'],temporal_evidence='dated_Wikimedia_dump_and_pre2022_Internet_Archive_presence_plus_revision_timestamps'),rights=dict(text_license=r['text_license'],scope='text-specific historical official policy; per-item exceptions and third-party quotations remain',commercial_reuse_license_candidate=True,attribution_required=True,share_alike_required=not is_news),format='MediaWiki XML in bzip2',size=dict(compressed_bytes=r['compressed_bytes'],expanded_bytes=r['expanded_bytes']),counts=rep['counts'],count_scope='structural page/revision counts; not independently eligible model records',unit='main-namespace nonredirect page revision, grouped by event/work/copy lineage',author_role='collective authorship; dump contributor is latest editor only',assistance_status='unknown',model_admitted=False,risks=['unexpanded templates and source markup','translated and quoted material','same-event or geographic hierarchy dependence','near-copy and cross-source lineage audit pending','privacy and third-party rights screening pending']))
specs=[
 ('harttle-land','harttle/harttle.github.io','f08a4c0e4525c985a1e091f860524a794ce134b6','2021-07-17T06:42:38Z','CC-BY-4.0','README.md',2),
 ('wu-kan','wu-kan/wu-kan.github.io','96cc63b0569f82ceb7fb991b8846369267d9ebe4','2021-12-25T11:25:56Z','CC-BY-4.0','_config.yml',2),
 ('ddadaal','ddadaal/ddadaal.me','92be42e96af71699b7f8d7ef08b21b2f37092836','2021-12-31T09:55:40Z','CC-BY-SA-4.0','src/components/Footer/Brief.tsx',2),
 ('yihui','yihui/yihui.org','017635f6514ab5f7ed0cabd1ceab9701c49002a6','2021-12-25T05:57:49Z','CC-BY-NC-SA-4.0','README.md',5),
 ('ruanyf-weekly','ruanyf/weekly','02b029b018ec1221be64b374009e48d5c5167252','2021-12-31T01:09:24Z',None,None,6),
 ('xuanwo','Xuanwo/blog','f4c2b946ac7f4d5c977f45fb5ed5f7d91bcf5a91','2021-12-31T11:56:21Z',None,None,6),
]
for sid,repo,commit,date,license_code,notice,rank in specs:
    f=META/(repo.replace('/','__')+'.tree.json');t=json.load(open(f))['tree']
    if sid=='yihui': rows=[x for x in t if x['type']=='blob' and x['path'].startswith('content/cn/') and x['path'].endswith(('.md','.Rmd'))]
    elif sid=='ddadaal': rows=[x for x in t if x['type']=='blob' and re.fullmatch(r'contents/\d{8}[^/]+/cn\.md',x['path'])]
    elif sid=='ruanyf-weekly': rows=[x for x in t if x['type']=='blob' and re.fullmatch(r'docs/issue-\d+\.md',x['path'])]
    elif sid=='xuanwo':rows=[x for x in t if x['type']=='blob' and x['path'].startswith('content/zh-Hans/') and x['path'].endswith('.md')]
    else:rows=[x for x in t if x['type']=='blob' and x['path'].startswith('_posts/')]
    years=collections.Counter()
    for r in rows:
        m=re.search(r'(?:^|/)(?:\d{0})?(20\d\d|19\d\d)[-/0-9]',r['path'])
        years[m.group(1) if m else 'unresolved_from_path']+=1
    status='metadata_verified_three_representatives_exposed_diagnostic' if sid in ('harttle-land','wu-kan','ddadaal') else 'noncommercial_only_candidate' if sid=='yihui' else 'quarantined_unresolved_text_license'
    sources.append(dict(source_id=sid,priority=rank,status=status,source_family='independently_licensed_author_blog',genre=['technical_blog','personal_essay_candidate','retrospective_candidate'] if sid!='ruanyf-weekly' else ['curated_newsletter'],source_urls=['https://github.com/'+repo+'/tree/'+commit],version=dict(git_commit=commit,git_committer_timestamp=date,git_tree_sha1=tree_root_sha1(json.load(open(f))),manifest_sha256=hashlib.sha256(f.read_bytes()).hexdigest(),temporal_evidence='maintainer_git_history_claim_and_content_addressed_objects; unsigned_commit_is_not_independent_timestamp'),rights=dict(text_license=license_code,license_notice_url=('https://github.com/'+repo+'/blob/'+commit+'/'+notice) if notice else None,scope='explicit prose notice' if license_code else 'not established',commercial_reuse_license_candidate=license_code in ('CC-BY-4.0','CC-BY-SA-4.0'),third_party_exceptions=True),format='Markdown/RMarkdown source',size=dict(candidate_source_bytes=sum(x['size'] for x in rows)),counts=dict(candidate_files=len(rows),path_stems=len({x['path'].rsplit('.',1)[0] for x in rows}),unique_git_blobs=len({x['sha'] for x in rows}),path_year_histogram=dict(years)),count_scope='candidate files, not admitted Chinese prose or independent authors/works',unit='one original post/work; Rmd/rendered versions and translations share lineage',author_role='site author attribution, not per-passage verified composition',assistance_status='unknown',model_admitted=False,risks=['code, homework, quoted texts, translations and tutorial series','one author per site and source-author confounding','individual original-prose and privacy screening pending','no proof of unaided human production']))
sources.append(dict(source_id='wikiconv-2017-expanded-frame',priority=2,status='existing_archive_metadata_capacity_only_new_protocol_required',source_family='wikimedia_discussion',genre=['internet_discussion'],source_urls=['https://figshare.com/articles/dataset/WikiConv_-_Chinese/7376012','https://github.com/conversationai/wikidetox/tree/main/wikiconv'],version=dict(archive_sha256='635500ba887cef0c9d2bfaef03659de2974b5fd84b8a0cd90a9bd7bdef7f492a'),rights=dict(text_license='CC-BY-SA-3.0',metadata_license='CC0',scope='maintainer content-specific notice; generic repository/release badge not controlling'),format='annual JSONL in ZIP',size=dict(existing_compressed_bytes=80074478,existing_expanded_bytes=871024181,new_download_bytes=0),counts=json.load(open(BASE/'public/wikiconv-metadata-capacity.json'))['counts'],count_scope='known-component ceilings before new unit/language/role/near-copy eligibility',unit='one within-record source view per merged lineage component',author_role='speaker metadata may not be original or sole author',assistance_status='unknown',model_admitted=False,risks=['new protocol needed for wider within-record frame','all old192 plus exposed groups and future connecting edges excluded; old32 is a consumed benchmark, not a fresh holdout','cross-year annual views and edit/restoration families are dependent']))
sources.append(dict(source_id='pmc-zh-published-through-2021',priority=3,status='metadata_only_historical_bytes_unverified',source_family='academic_publisher_deposits',genre=['research_article','review_article'],source_urls=['https://pmc.ncbi.nlm.nih.gov/tools/pmcaws/','https://pmc.ncbi.nlm.nih.gov/tools/oai/'],version=dict(query_checked_on='2026-10-01',query_result_sha256=hashlib.sha256((META/'pmc-pre2022-ccby-esearch.json').read_bytes()).hexdigest(),historical_archive_id=None,historical_text_sha256=None),rights=dict(text_license='article-level CC-BY candidates; exact URI and exceptions required',scope='per article/version'),format='JATS XML, PDF, JSON metadata',size=None,counts=dict(current_query_records=2074,verified_pre2022_text_versions_this_round=0),count_scope='current ESearch metadata, neither immutable historic texts nor independent usable works',query='chi[la] AND "cc by license"[filter] AND ("1900/01/01"[dp] : "2021/12/31"[dp]) NOT "pmc embargo"[filter]',unit='DOI/PMCID work family, not abstract/paragraph/translation',author_role='coauthor team, editors/translators distinct; no first-author prose attribution',assistance_status='unknown',model_admitted=False,risks=['PMC content can update without version bump','S3 LastModified can reflect metadata reprocessing','legacy oa.fcgi and bulk FTP/Cloud paths retired in August2026','clinical privacy, retractions and third-party content','biomedical selection limits broad academic genre claim']))
sources.append(dict(source_id='gutenberg-modern-essays',priority=4,status='catalogue_leads_historical_digital_version_pending',source_family='public_domain_literary_editions',genre=['literary_essay','prose_poem'],source_urls=['https://www.gutenberg.org/ebooks/25271','https://www.gutenberg.org/ebooks/25242','https://www.gutenberg.org/policy/robot_access.html'],version=dict(ebook_ids=[25271,25242],maintainer_release_year=2008,maintainer_last_update='2021-01-03',historical_text_sha256=None),rights=dict(text_license='item-level public-domain assertion, jurisdiction and edition rights must be checked',scope='PG metadata license does not confer text license'),format='source plain text/HTML; avoid treating periodically regenerated cache as historical bytes',size=None,counts=dict(identified_ebooks=2,verified_independent_essay_units=0),unit='bibliographically independent work, chapters/volumes not automatically independent',author_role='original author versus transcriber/editor/translator',assistance_status='unknown',model_admitted=False,risks=['generated formats rebuilt monthly','book-versus-essay lineage and duplicate editions','historical script/typography and modern editing confounds','use supported robot/mirror channels; no ordinary-site bulk crawler']))
for ident in ['zhwiki-20211120','zhwikisource-20211220']:
    a=json.load(open(META/(ident+'.json')));f=next(x for x in a['files'] if x['name'].endswith('-pages-articles.xml.bz2'))
    sources.append(dict(source_id=ident,priority=5,status='metadata_only_over_acquisition_cap',source_urls=['https://archive.org/metadata/'+ident],version=dict(snapshot_date=a['metadata']['date'],archive_publicdate=a['metadata']['publicdate'],sha1=f['sha1'],md5=f['md5'],sha256=None),rights=dict(text_license='CC-BY-SA-3.0 historical Wikipedia; Wikisource requires per-work public-domain/license verification',scope='not a blanket license for all historical source editions'),format='MediaWiki XML.bz2',size=dict(compressed_bytes=int(f['size'])),counts=None,model_admitted=False))
catalogue=dict(schema_version='style-pre2022-source-catalogue/1.0',created_at='2026-10-01T17:15:44.068396+00:00',cutoff_exclusive='2022-01-01T00:00:00Z',target_training_records=1280,proposed_total_candidate_components_before_new_splits=[1800,2000],acquisition_caps=dict(new_download_bytes=100000000,expanded_bytes=500000000),model_fit_performed=False,old_sealed_test_text_read=False,personal_author_stage_accessed=False,public_safe=True,sources=sources)
(BASE/'public/catalogue.json').write_text(json.dumps(catalogue,ensure_ascii=False,indent=2)+'\n')
print('catalogue sources',len(sources))
